name = "aoc"
author = "Evann (Estym) Regnault"
version = "1.0.0"

[dependencies]
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
nibble = ">= 1.1.1 and < 2.0.0"
gleam_otp = ">= 0.12.1 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

